[package]
name = "jstime"
version = "0.13.4-alpha.0"
description = "Another JS Runtime"
readme = "README.md"
license = "Apache-2.0"
authors = ["the jstime authors"]
edition = "2018"
repository = "https://github.com/jstime/jstime"
default-run = "jstime"

[[bin]]
name = "jstime"
path = "main.rs"

[dependencies]
jstime_core = { path = "../core", version = "^0.13.4"}
rustyline = "6.3.0"
structopt = "0.3.17"
dirs = "3.0.1"

[build-dependencies]
jstime_core = { path = "../core", version = "^0.13.4"}

[package.metadata.release]
tag-prefix = ""
