[package]
name = "jstime"
version = "0.40.0"
description = "Another JS Runtime"
readme = "README.md"
license = "Apache-2.0"
authors = ["the jstime authors"]
edition = "2018"
repository = "https://github.com/jstime/jstime"
default-run = "jstime"

[[bin]]
name = "jstime"
path = "main.rs"

[dependencies]
jstime_core = { path = "../core", version = "^0.40.0"}
rustyline = "9.1.2"
structopt = "0.3.26"
dirs = "4.0.0"

[build-dependencies]
jstime_core = { path = "../core", version = "^0.40.0"}

[dev-dependencies]
assert_cmd = "2.0.4"
predicates = "2.1.1"

[package.metadata.release]
tag-prefix = ""
