[package]
name = "jstime_core"
version = "0.12.3"
description = "Another JS Runtime"
readme = "README.md"
license = "Apache-2.0"
authors = ["the jstime authors"]
edition = "2018"
repository = "https://github.com/jstime/jstime"

[dependencies]
rusty_v8 = "0.8.1"

[package.metadata.release]
disable-tag = true
