[package]
name = "jstime_core"
version = "0.50.0"
description = "Another JS Runtime"
readme = "README.md"
license = "Apache-2.0"
authors = ["the jstime authors"]
edition = "2021"
repository = "https://github.com/jstime/jstime"

[dependencies]
v8 = "0.85.0"
lazy_static = "1.4.0"

[package.metadata.release]
tag = false
